import test from "node:test"
import assert from "node:assert/strict"
import { load, renderMembers, renderStaff, renderMemberDetail, renderVolunteer, renderApplicationList, renderHome, renderCalendar, renderDonations, renderDonate, renderContact, renderAdoption, renderMyApplications } from "./helpers/page-review-fixtures.mjs"

test("member list returns preserve only validated internal filters", () => {
  const { memberListReturnHref: back } = load("src/features/members/lib/list-navigation.ts")
  for (const value of ["https://evil.test", "//evil.test", "/admin/members/../admins", "/admin/members/other", "/admin/members\\other"]) assert.equal(back(value), "/admin/members")
  assert.equal(back("/admin/admins"), "/admin/admins")
  assert.equal(back("/admin/admins?unsafe=1"), "/admin/members")
  const url = new URL(back("/admin/members?q=모임&status=pending&sort=joined&page=3&extra=unsafe"), "https://example.test")
  assert.equal(url.searchParams.get("q"), "모임")
  assert.equal(url.searchParams.get("page"), "3")
  assert.equal(url.searchParams.get("extra"), null)
})
test("application filter toolbar is always visible, latest-first and keeps date inputs", () => {
  for (const type of ["volunteer", "adoption"]) {
    const html = renderApplicationList({ type, sort: "oldest", from: "2026-10-01", to: "2026-10-07", q: "김" })
    assert.doesNotMatch(html, /<details|기간·정렬|name="sort"|오래된 신청|일정변경 요청을 먼저/)
    assert.match(html, /접수 최신순/)
    assert.match(html, /name="q"[^>]*value="김"/)
    assert.match(html, /<input(?=[^>]*type="date")(?=[^>]*name="from")(?=[^>]*value="2026-10-01")[^>]*>/)
    assert.match(html, /<input(?=[^>]*type="date")(?=[^>]*name="to")(?=[^>]*value="2026-10-07")[^>]*>/)
    assert.match(html, /name="dateBy"/)
  }
})
test("mobile applications keep one submitted status value and bounded date inputs", () => {
  const html = renderApplicationList({ status: "승인", q: "김" })
  assert.equal((html.match(/name="status"/g) || []).length, 1)
  assert.equal((html.match(/application-date-input/g) || []).length, 2)
  assert.match(html, /<option[^>]*selected[^>]*>승인/)
  assert.match(html, /grid-cols-1 items-end/)
  assert.equal((html.match(/h-11 min-h-11/g) || []).length, 5)
  assert.match(html, /aria-label="처리 상태"/)
})
test("application schedule labels split date and time and keep timestamps in Korea time", async () => {
  for (const options of [{}, { status: "승인", registered: true }, { status: "일정변경요청", registered: true }]) {
    const html = await renderVolunteer(options)
    assert.match(html, />날짜:<\/dt>/)
    assert.match(html, />시간:<\/dt>/)
    assert.match(html, />26\.10\.24<\/dd>/)
    assert.match(html, />15:00<\/dd>/)
  }
  const html = renderApplicationList({}, [{ id: "sample", applicant_name: "예시", phone: "010-0000-0000", status: "접수", submitted_at: "2026-10-08T07:00:00Z", party_size: 2, available_dates: ["2026-10-17", "2026-10-18"], available_time: "14:00", linkedCount: 0 }])
  assert.equal((html.match(/>날짜:<\/dt>/g) || []).length, 2)
  assert.equal((html.match(/>시간:<\/dt>/g) || []).length, 2)
  assert.match(html, />26\.10\.17<\/dd>/)
})

test("mobile status selector submits the containing search form without dropping its fields", () => {
  const { ApplicationStatusFilter } = load("src/features/applications/components/application-status-filter.tsx")
  let submits = 0
  const element = ApplicationStatusFilter({ value: "접수", statuses: ["접수", "검토중"], className: "" })
  element.props.onChange({ currentTarget: { form: { requestSubmit: () => submits++ } } })
  assert.equal(submits, 1)
  assert.equal(element.props.name, "status")
})
test("home volunteer actions use matching buttons without arrow and retain first-visit guidance", async () => {
  const html = await renderHome()
  const banner = html.slice(html.indexOf("함께하는 방법"), html.indexOf('aria-label="후원 계좌 안내"'))
  assert.match(banner, /href="\/volunteer"[^>]*>봉사 신청하기<\/a>/)
  assert.match(banner, /href="#volunteer-calendar"[^>]*>봉사 일정 확인<\/a>/)
  assert.match(banner, /href="\/about"[^>]*>첫 방문 안내<\/a>/)
  assert.doesNotMatch(banner, /↗|일정 먼저 보기/)
  assert.match(html, /id="volunteer-calendar"/)
})
test("staff calendar selected event is a whole-row detail link without a separate management button", () => {
  const html = renderCalendar()
  assert.match(html, /<a href="\/admin\/applications\/volunteer\/application" aria-label="김\*\* · 봉사 신청 상세 보기"[^>]*><div[^>]*>.*김\*\*/s)
  assert.doesNotMatch(html, />관리하기<|>봉사 신청 상세 보기<|>내 신청 보기</)
  assert.match(html, /focus-visible:outline-ring/)
  const member = renderCalendar({ wholeRow: false })
  assert.match(member, />내 신청 보기<\/a>/)
  assert.doesNotMatch(member, /href="\/admin\/applications/)
  const guest = renderCalendar({ linked: false })
  assert.doesNotMatch(guest, /href="\/admin\/applications|>내 신청 보기<\/a>/)
})
test("member list renders visible state, contact and detail links without a forced wide table", async () => {
  const html = await renderMembers({ q: "모임", status: "pending", page: "3" })
  assert.match(html, /차단됨/)
  assert.match(html, /가입 미완료/)
  assert.doesNotMatch(html, /상세 관리/)
  assert.match(html, /xl:col-start-2 xl:row-start-1/)
  assert.doesNotMatch(html, /min-w-\[600px\]|<select[^>]*권한/)
  assert.match(html, /returnTo=/)
  assert.match(html, /page%3D3/)
})
test("donation filters retain search and mobile rows retain status and type", async () => {
  const html = await renderDonations({ q: "모임", type: "cash", page: "3" })
  assert.match(html, /status=pending&amp;type=cash&amp;q=/)
  assert.match(html, /검토중/)
  assert.match(html, /기록완료/)
  assert.match(html, /현금/)
  assert.match(html, /물품/)
  assert.doesNotMatch(html, /hidden text-right sm:block/)
})
test("staff list shares member layout, has no inline management and returns to staff list", async () => {
  const html = await renderStaff()
  assert.match(html, /returnTo=%2Fadmin%2Fadmins/)
  assert.match(html, /전화번호/)
  assert.doesNotMatch(html, /<table|<select|상세 관리|운영진 제거/)
  assert.match(html, /xl:col-start-2 xl:row-start-1/)
})
test("member details retain information and management in independent desktop columns", async () => {
  const html = await renderMemberDetail()
  assert.match(html, /기본 정보/)
  assert.match(html, /회원 권한·승인·차단/)
  assert.match(html, /contents xl:flex/)
  assert.doesNotMatch(html, /row-span-/)
  assert.match(html, /<details[^>]*>.*약관 동의 정보/s)
  assert.match(html, /href="\/admin\/members\?page=3&amp;q=/)
})
test("staff detail preserves role and confirmed removal controls; own role stays disabled", async () => {
  const html = await renderMemberDetail({ staff: true })
  assert.match(html, /href="\/admin\/admins"/)
  assert.match(html, /운영진 해제/)
  const self = await renderMemberDetail({ staff: true, self: true })
  assert.match(self, /<select[^>]*disabled/)
  assert.doesNotMatch(self, />운영진 해제<\/button>/)
})
test("own application schedules are scoped to owned IDs and display actual calendar time", async () => {
  const { html, calls } = await renderMyApplications()
  assert.ok(calls.some(([table, key, value]) => table === "volunteer_applications" && key === "created_by" && value === "member"))
  assert.ok(calls.some(([table, key, value]) => table === "events" && key === "source_application_id" && value[0] === "own"))
  assert.match(html, /26\. 10\. 19\. 15:00/)
  assert.match(html, /승인 전까지 기존 확정 일정/)
  assert.match(html, /id="volunteer-own" open=""/)
  assert.match(html, /준비물 · 운영진 안내/)
  const failed = await renderMyApplications({ eventError: true })
  assert.match(failed.html, /확정 일정을 불러오지 못했습니다/)
  assert.doesNotMatch(failed.html, /href="\/my\/applications\/volunteer\/own\/edit"/)
})
test("public guidance puts account and directions first and preserves expense access", async () => {
  const donate = await renderDonate()
  assert.ok(donate.indexOf("계좌 후원") < donate.indexOf("후원금은 이렇게"))
  assert.match(donate, /href="\/expenses"/)
  assert.doesNotMatch(donate, /🌱|💛/)
  const contact = renderContact()
  assert.ok(contact.indexOf("보호소 주소") < contact.indexOf(">문의 방법</h2>"))
  assert.match(contact, /카카오톡 상담/)
})
test("adoption detail uses independent columns and early mobile processing", async () => {
  const html = await renderAdoption()
  assert.match(html, /contents xl:flex/)
  assert.match(html, /id="application-processing" class="order-2/)
  assert.match(html, /<details[^>]*>.*신청 시 동의/s)
})
test("volunteer summary distinguishes approved without schedule and shows application data before processing", async () => {
  const pending = await renderVolunteer()
  assert.match(pending, /접수 · 승인 대기/)
  assert.ok(pending.indexOf("010-0000-1201") < pending.indexOf('id="application-processing"'))
  assert.ok(pending.indexOf("신청 일시") > pending.indexOf('id="application-processing"'))
  const approved = await renderVolunteer({ status: "승인", registered: true })
  assert.match(approved, /승인 완료/)
  assert.match(approved, /캘린더에 봉사 일정 1건이 등록/)
  assert.doesNotMatch(approved, /type="submit"/)
  const missing = await renderVolunteer({ status: "승인" })
  assert.match(missing, /신청은 승인됐지만 캘린더 일정은 없습니다/)
  assert.match(missing, /일정 등록<\/a>/)
  await assert.rejects(() => renderVolunteer({ eventError: true }), /불러오지 못했습니다/)
})
